#!/bin/bash
# SahayakAI Deployment Guide

echo "========================================"
echo "   SahayakAI Deployment Helper"
echo "========================================"
echo ""
echo "1. GitHub Repo is Ready: https://github.com/YOUFYI/SahayakAI"
echo ""
echo "2. Deploy to Render:"
echo "   - Log in to https://dashboard.render.com/"
echo "   - Click 'New +' -> 'Web Service'"
echo "   - Connect your GitHub account and select 'SahayakAI'"
echo "   - Render will detect 'render.yaml' and auto-configure."
echo "   - OR Manually:"
echo "       * Build Command: pip install -r backend/requirements.txt"
echo "       * Start Command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "3. Environment Variables (Critical):"
echo "   - You MUST add these in Render Dashboard:"
echo "       * GROQ_API_KEY = (Your Key)"
echo "       * HF_TOKEN = (Your Hugging Face Token)"
echo "       * PYTHON_VERSION = 3.10.0"
echo ""
echo "========================================"
