"""
Presentation Generator using python-pptx (Open Source)
Creates PowerPoint presentations for educational content
"""
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RgbColor
from pptx.enum.text import PP_ALIGN
import os

def create_presentation(title: str, slides_content: list, filename: str) -> str:
    """
    Create a PowerPoint presentation from content.
    
    Args:
        title: Presentation title
        slides_content: List of dicts with 'title' and 'content' keys
        filename: Output filename (without extension)
    
    Returns:
        Path to generated file
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title_shape = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title_shape.text = title
    subtitle.text = "Generated by Sahayak.AI - Your Teaching Companion"
    
    # Content Slides
    content_layout = prs.slide_layouts[1]  # Title and Content
    
    for slide_data in slides_content:
        slide = prs.slides.add_slide(content_layout)
        slide.shapes.title.text = slide_data.get('title', 'Untitled')
        
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.text = slide_data.get('content', '')
        
        # Format text
        for paragraph in tf.paragraphs:
            paragraph.font.size = Pt(18)
    
    # Save
    output_path = f"/tmp/{filename}.pptx"
    prs.save(output_path)
    return output_path


def create_lesson_presentation(topic: str, content: str) -> str:
    """
    Quick helper to create a lesson presentation from markdown-like content.
    Splits content by headers (###) into individual slides.
    """
    slides = []
    sections = content.split('###')
    
    for section in sections:
        if section.strip():
            lines = section.strip().split('\n', 1)
            title = lines[0].replace('**', '').strip()
            body = lines[1].strip() if len(lines) > 1 else ""
            slides.append({'title': title, 'content': body[:500]})  # Limit content per slide
    
    if not slides:
        slides = [{'title': topic, 'content': content[:500]}]
    
    return create_presentation(topic, slides, topic.replace(' ', '_').lower())


if __name__ == "__main__":
    # Test
    test_slides = [
        {'title': 'What is Photosynthesis?', 'content': 'The process by which plants convert light energy into chemical energy.'},
        {'title': 'Key Components', 'content': 'Chlorophyll, Sunlight, Water, Carbon Dioxide'},
        {'title': 'The Equation', 'content': '6CO2 + 6H2O + light → C6H12O6 + 6O2'}
    ]
    path = create_presentation("Photosynthesis", test_slides, "test_presentation")
    print(f"Created: {path}")
